# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 09:15
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import lotto.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawdate', models.DateTimeField()),
                ('prize', models.DecimalField(decimal_places=2, max_digits=20)),
                ('winning_combo', lotto.models.LotteryNumberField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('entry', lotto.models.LotteryNumberField(blank=None)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotto.Draw')),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.CreateModel(
            name='LotteryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number_of_numbers', models.PositiveIntegerField()),
                ('max_val', models.PositiveIntegerField()),
                ('rollover', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('min_matches', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Punter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Win',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.DecimalField(decimal_places=2, max_digits=20)),
                ('wintype', models.CharField(choices=[('M', 'main'), ('S', 'spotprize')], default='M', max_length=1)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lotto.Entry')),
            ],
        ),
        migrations.CreateModel(
            name='MoreComplexLottery',
            fields=[
                ('lotterytype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lotto.LotteryType')),
                ('spotprize_nummatches', models.PositiveIntegerField()),
                ('spotprize_value', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'verbose_name': 'More Complex Lottery Type',
                'verbose_name_plural': 'More Complex Lottery Types',
            },
            bases=('lotto.lotterytype',),
        ),
        migrations.CreateModel(
            name='SimpleLottery',
            fields=[
                ('lotterytype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lotto.LotteryType')),
            ],
            options={
                'verbose_name': 'Simple Lottery Type',
                'verbose_name_plural': 'Simple Lottery Types',
            },
            bases=('lotto.lotterytype',),
        ),
        migrations.AddField(
            model_name='entry',
            name='punter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotto.Punter'),
        ),
        migrations.AddField(
            model_name='draw',
            name='lotterytype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotto.LotteryType'),
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([('punter', 'draw')]),
        ),
    ]
