# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('entry', models.CommaSeparatedIntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawdate', models.DateTimeField()),
                ('prize', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='LotteryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_numbers', models.IntegerField()),
                ('max_val', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Punter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Win',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.DecimalField(decimal_places=2, max_digits=20)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotto.Entry')),
                ('punter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotto.Punter')),
            ],
        ),
        migrations.AddField(
            model_name='lottery',
            name='lotterytype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotto.LotteryType'),
        ),
        migrations.AddField(
            model_name='entry',
            name='lottery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotto.Lottery'),
        ),
        migrations.AddField(
            model_name='entry',
            name='punter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotto.Punter'),
        ),
    ]
