# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterModelOptions(
            name='lottery',
            options={'verbose_name_plural': 'Lotteries'},
        ),
        migrations.AddField(
            model_name='lottery',
            name='winning_combo',
            field=models.CommaSeparatedIntegerField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
