# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0003_auto_20160201_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='winning_combo',
            field=models.CommaSeparatedIntegerField(blank=True, max_length=100),
        ),
    ]
