# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0004_auto_20160201_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotterytype',
            name='name',
            field=models.CharField(default='short and sweet', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lotterytype',
            name='rollover',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([('punter', 'lottery')]),
        ),
    ]
