# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0005_auto_20160201_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotterytype',
            name='min_matches',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lotterytype',
            name='rollover',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=20),
        ),
    ]
