# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0006_auto_20160201_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottery',
            name='winning_combo',
        ),
        migrations.AddField(
            model_name='lottery',
            name='_winning_combo',
            field=models.CommaSeparatedIntegerField(blank=True, db_column='winning_combo', max_length=100),
        ),
    ]
