# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0007_auto_20160201_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='entry',
        ),
        migrations.AddField(
            model_name='entry',
            name='_entry',
            field=models.CommaSeparatedIntegerField(db_column='entry', default=(1, 2, 3), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
