# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0008_auto_20160202_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='_entry',
            field=models.CommaSeparatedIntegerField(db_column='entry', default=None, max_length=100),
        ),
    ]
