# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0010_auto_20160202_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='win',
            name='entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lotto.Entry'),
        ),
    ]
