# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0011_auto_20160202_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleLottery',
            fields=[
                ('lotterytype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lotto.LotteryType')),
            ],
            bases=('lotto.lotterytype',),
        ),
    ]
