# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0013_auto_20160202_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='win',
            name='wintype',
            field=models.CharField(choices=[(b'main', 'E'), (b'spotprize', 'S')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
