# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0014_win_wintype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='win',
            name='wintype',
            field=models.CharField(choices=[('M', 'main'), ('S', 'spotprize')], default='M', max_length=1),
        ),
    ]
