# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0015_auto_20160203_1600'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lottery',
            new_name='Draw',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='lottery',
            new_name='draw',
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([('punter', 'draw')]),
        ),
    ]
