# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0016_auto_20160203_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draw',
            options={},
        ),
        migrations.AddField(
            model_name='punter',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='punter',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
